In [1]:
from futu import *
import pandas as pd 
from queue import Queue
from quant.data.sqlitdatahandler import SQLiteDataHandler
from quant.backtest import Backtest


plate = ['HK.BK1001', 'HK.BK1002', 'HK.BK1003', 'HK.BK1004', 'HK.BK1005', 'HK.BK1007', 'HK.BK1008', 'HK.BK1009', 
         'HK.BK1010', 'HK.BK1011', 'HK.BK1012', 'HK.BK1013', 'HK.BK1014', 'HK.BK1015', 'HK.BK1016', 'HK.BK1017', 
         'HK.BK1019', 'HK.BK1020', 'HK.BK1021', 'HK.BK1022', 'HK.BK1025', 'HK.BK1026', 'HK.BK1027', 'HK.BK1028', 
         'HK.BK1029', 'HK.BK1030', 'HK.BK1031', 'HK.BK1032', 'HK.BK1033', 'HK.BK1034', 'HK.BK1035', 'HK.BK1037', 
         'HK.BK1039', 'HK.BK1040', 'HK.BK1041', 'HK.BK1042', 'HK.BK1043', 'HK.BK1044', 'HK.BK1045', 'HK.BK1046', 
         'HK.BK1047', 'HK.BK1048', 'HK.BK1049', 'HK.BK1050', 'HK.BK1051', 'HK.BK1052', 'HK.BK1053', 'HK.BK1054', 
         'HK.BK1055', 'HK.BK1056', 'HK.BK1058', 'HK.BK1059', 'HK.BK1061', 'HK.BK1062', 'HK.BK1063', 'HK.BK1064', 
         'HK.BK1065', 'HK.BK1066', 'HK.BK1067', 'HK.BK1068', 'HK.BK1069', 'HK.BK1070', 'HK.BK1071', 'HK.BK1072', 
         'HK.BK1073', 'HK.BK1074', 'HK.BK1075', 'HK.BK1076', 'HK.BK1077', 'HK.BK1078', 'HK.BK1079', 'HK.BK1080', 
         'HK.BK1082', 'HK.BK1083', 'HK.BK1084', 'HK.BK1086', 'HK.BK1087', 'HK.BK1089', 'HK.BK1090', 'HK.BK1091', 
         'HK.BK1093', 'HK.BK1094', 'HK.BK1095', 'HK.BK1096', 'HK.BK1097', 'HK.BK1098', 'HK.BK1099', 'HK.BK1100']

events = Queue()
sdh = SQLiteDataHandler(plate, events, '2020-01-01', sqllite_db="test1.db")

2020-05-31 20:13:37,860 [open_context_base.py] _socket_reconnect_and_wait_ready:257: Start connecting: host=127.0.0.1; port=11111;
2020-05-31 20:13:37,862 [open_context_base.py] on_connected:346: Connected : conn_id=1;
2020-05-31 20:13:37,864 [open_context_base.py] _handle_init_connect:447: InitConnect ok: conn_id=1; info={'server_version': 212, 'login_user_id': 7659870, 'conn_id': 6672832393589172252, 'conn_key': 'AF1D2BA9B190484C', 'conn_iv': 'CAFDF6067AE46602', 'keep_alive_interval': 10, 'is_encrypt': False};

start sqlite ...
start futu ...

In [2]:
#sdh.build_local_kline_db()

HK.800000 download kline finished!
HK.BK1001 download kline finished!
HK.BK1002 download kline finished!
HK.BK1003 download kline finished!
HK.BK1004 download kline finished!
HK.BK1005 download kline finished!
HK.BK1007 download kline finished!
HK.BK1008 download kline finished!
HK.BK1009 download kline finished!
HK.BK1010 download kline finished!
HK.BK1011 download kline finished!
HK.BK1012 download kline finished!
HK.BK1013 download kline finished!
HK.BK1014 download kline finished!
HK.BK1015 download kline finished!
HK.BK1016 download kline finished!
HK.BK1017 download kline finished!
HK.BK1019 download kline finished!
HK.BK1020 download kline finished!
HK.BK1021 download kline finished!
HK.BK1022 download kline finished!
HK.BK1025 download kline finished!
HK.BK1026 download kline finished!
HK.BK1027 download kline finished!
HK.BK1028 download kline finished!
HK.BK1029 download kline finished!
HK.BK1030 download kline finished!
HK.BK1031 download kline finished!
HK.BK1032 download kline finished!
HK.BK1033 download kline finished!
HK.BK1034 download kline finished!
HK.BK1035 download kline finished!
HK.BK1037 download kline finished!
HK.BK1039 download kline finished!
HK.BK1040 download kline finished!
HK.BK1041 download kline finished!
HK.BK1042 download kline finished!
HK.BK1043 download kline finished!
HK.BK1044 download kline finished!
HK.BK1045 download kline finished!
HK.BK1046 download kline finished!
HK.BK1047 download kline finished!
HK.BK1048 download kline finished!
HK.BK1049 download kline finished!
HK.BK1050 download kline finished!
HK.BK1051 download kline finished!
HK.BK1052 download kline finished!
HK.BK1053 download kline finished!
HK.BK1054 download kline finished!
HK.BK1055 download kline finished!
HK.BK1056 download kline finished!
HK.BK1058 download kline finished!
HK.BK1059 download kline finished!
HK.BK1061 download kline finished!
HK.BK1062 download kline finished!
HK.BK1063 download kline finished!
HK.BK1064 download kline finished!
HK.BK1065 download kline finished!
HK.BK1066 download kline finished!
HK.BK1067 download kline finished!
HK.BK1068 download kline finished!
HK.BK1069 download kline finished!
HK.BK1070 download kline finished!
HK.BK1071 download kline finished!
HK.BK1072 download kline finished!
HK.BK1073 download kline finished!
HK.BK1074 download kline finished!
HK.BK1075 download kline finished!
HK.BK1076 download kline finished!
HK.BK1077 download kline finished!
HK.BK1078 download kline finished!
HK.BK1079 download kline finished!
HK.BK1080 download kline finished!
HK.BK1082 download kline finished!
HK.BK1083 download kline finished!
HK.BK1084 download kline finished!
HK.BK1086 download kline finished!
HK.BK1087 download kline finished!
HK.BK1089 download kline finished!
HK.BK1090 download kline finished!
HK.BK1091 download kline finished!
HK.BK1093 download kline finished!
HK.BK1094 download kline finished!
HK.BK1095 download kline finished!
HK.BK1096 download kline finished!
HK.BK1097 download kline finished!
HK.BK1098 download kline finished!
HK.BK1099 download kline finished!
HK.BK1100 download kline finished!

In [2]:
#sdh.build_local_basicinfo_db()

HK.BK1001 乳制品 done!
HK.BK1002 供应链管理 done!
HK.BK1003 保险 done!
HK.BK1004 信贷 done!
HK.BK1005 公共运输 done!
HK.BK1007 其他金融 done!
HK.BK1008 农业产品 done!
HK.BK1009 出版 done!
HK.BK1010 包装食品 done!
HK.BK1011 化肥农药 done!
HK.BK1012 医疗设备 done!
HK.BK1013 半导体 done!
HK.BK1014 卫星通讯 done!
HK.BK1015 印刷包装 done!
HK.BK1016 可再生能源 done!
HK.BK1017 商业用车 done!
HK.BK1019 地产发展商 done!
HK.BK1020 地产投资 done!
HK.BK1021 家具 done!
HK.BK1022 家庭电器 done!
HK.BK1025 工业器材 done!
HK.BK1026 广告及宣传 done!
HK.BK1027 广播 done!
HK.BK1028 建筑材料 done!
HK.BK1029 影视娱乐 done!
HK.BK1030 投资及资管 done!
HK.BK1031 支援服务 done!
HK.BK1032 文娱设施 done!
HK.BK1033 新能源物料 done!
HK.BK1034 旅游观光 done!
HK.BK1035 纺织服饰 done!
HK.BK1037 林业木材 done!
HK.BK1039 水务 done!
HK.BK1040 汽车 done!
HK.BK1041 汽车零件 done!
HK.BK1042 油气生产商 done!
HK.BK1043 油气设备 done!
HK.BK1044 煤炭 done!
HK.BK1045 燃气供应 done!
HK.BK1046 特殊化工品 done!
HK.BK1047 文体休闲用品 done!
HK.BK1048 环保工程 done!
HK.BK1049 珠宝钟表 done!
HK.BK1050 生物科技 done!
HK.BK1051 电力 done!
HK.BK1052 电子消费品 done!
HK.BK1053 电脑器材 done!
HK.BK1054 电讯服务 done!
HK.BK1055 电话设备及元件 done!
HK.BK1056 百货商城 done!
HK.BK1058 电商及互联网 done!
HK.BK1059 纸及纸制品 done!
HK.BK1061 综合企业 done!
HK.BK1062 美容护理 done!
HK.BK1063 航天军工 done!
HK.BK1064 航空服务 done!
HK.BK1065 航空物流 done!
HK.BK1066 航运及港口 done!
HK.BK1067 药品 done!
HK.BK1068 证券经纪 done!
HK.BK1069 博彩概念 done!
HK.BK1070 超市便利店 done!
HK.BK1071 酒店度假村 done!
HK.BK1072 酒精饮料 done!
HK.BK1073 重型基建 done!
HK.BK1074 重机械 done!
HK.BK1075 钢铁 done!
HK.BK1076 铁路公路 done!
HK.BK1077 铜 done!
HK.BK1078 铝 done!
HK.BK1079 银行 done!
HK.BK1080 非酒精饮料 done!
HK.BK1082 食品添加剂 done!
HK.BK1083 餐饮 done!
HK.BK1084 黄金贵金属 done!
HK.BK1086 医疗及医美 done!
HK.BK1087 房地产信托 done!
HK.BK1089 地产代理 done!
HK.BK1090 物业管理 done!
HK.BK1091 教育 done!
HK.BK1093 殡仪服务 done!
HK.BK1094 建筑工程 done!
HK.BK1095 建筑服务 done!
HK.BK1096 装修与设计 done!
HK.BK1097 系统软件 done!
HK.BK1098 资讯科技服务 done!
HK.BK1099 应用软件 done!
HK.BK1100 游戏软件 done!

In [2]:
sdh.update_local_kline_db()
sdh.load_kline_from_local_db()
sdh.init_hist_time_line()
sdh.load_basicinfo_from_local_db()

In [3]:
sdh.hist_index, sdh.cur_datetime, len(sdh.hist_time_line), len(sdh.hist_kline)

(2213, '2019-12-31', 2315, 89)

In [4]:
sdh.update_bars()

In [42]:
sdh.snapshot

,open,close,high,low,pe_ratio,turnover_rate,volume,turnover,change_rate,last_close
code,,,,,,,,,,
HK.800000,27999.580,28087.920,28198.610,27857.730,0.0,0.0,0,9.655395e+10,-0.826705,28322.060
HK.BK1001,1509.356,1547.672,1547.965,1509.356,0.0,0.0,13308053,1.853678e+08,0.618336,1538.161
HK.BK1002,312.447,311.230,313.366,305.109,0.0,0.0,20790000,2.023098e+06,-0.404806,312.495
HK.BK1003,1274.600,1271.237,1293.693,1266.992,0.0,0.0,187092061,6.500225e+09,-1.547987,1291.225
HK.BK1004,576.951,574.711,578.284,572.025,0.0,0.0,52718290,3.970076e+07,-0.539434,577.828
...,...,...,...,...,...,...,...,...,...,...
HK.BK1096,473.066,471.574,473.529,467.195,0.0,0.0,10799500,1.841442e+07,-0.343197,473.198
HK.BK1097,1249.095,1241.985,1276.535,1224.006,0.0,0.0,66877183,5.159415e+08,-0.327271,1246.063
HK.BK1098,1206.615,1219.871,1229.490,1206.615,0.0,0.0,52156057,1.349518e+08,-0.665045,1228.038
HK.BK1099,848.451,857.627,860.195,840.749,0.0,0.0,36391495,7.755236e+07,0.139065,856.436
HK.BK1100,899.337,896.266,909.265,889.678,0.0,0.0,52232357,2.597975e+08,-1.429616,909.265

In [43]:
sdh.get_latest_bar('HK.BK1001')

open             1.509356e+03
close            1.547672e+03
high             1.547965e+03
low              1.509356e+03
pe_ratio         0.000000e+00
turnover_rate    0.000000e+00
volume           1.330805e+07
turnover         1.853678e+08
change_rate      6.183358e-01
last_close       1.538161e+03
Name: HK.BK1001, dtype: float64

In [44]:
sdh.get_latest_bar_value('HK.BK1001', 'close')

1547.672

In [45]:
sdh.get_latest_datetime()

'2020-01-08'

In [46]:
sdh.get_latest_bars('HK.800000', 10)

,code,open,close,high,low,pe_ratio,turnover_rate,volume,turnover,change_rate,last_close
time_key,,,,,,,,,,,
2019-12-23,HK.800000,28024.62,27906.41,28024.62,27830.08,0.0,0.0,0,6.555081e+10,0.125792,27871.35
2019-12-24,HK.800000,27901.51,27864.21,27921.29,27792.66,0.0,0.0,0,3.198449e+10,-0.151220,27906.41
2019-12-27,HK.800000,28033.66,28225.42,28226.11,28000.62,0.0,0.0,0,7.492620e+10,1.296322,27864.21
2019-12-30,HK.800000,28250.48,28319.39,28418.65,28165.13,0.0,0.0,0,7.676305e+10,0.332927,28225.42
2019-12-31,HK.800000,28241.43,28189.75,28298.46,28123.86,0.0,0.0,0,4.843351e+10,-0.457778,28319.39
2020-01-02,HK.800000,28249.37,28543.52,28543.52,28245.97,0.0,0.0,0,9.087495e+10,1.254960,28189.75
2020-01-03,HK.800000,28828.36,28451.50,28883.30,28428.17,0.0,0.0,0,9.788683e+10,-0.322385,28543.52
2020-01-06,HK.800000,28326.50,28226.19,28367.87,28054.29,0.0,0.0,0,9.160570e+10,-0.791909,28451.50
2020-01-07,HK.800000,28352.68,28322.06,28473.08,28264.07,0.0,0.0,0,8.641908e+10,0.339649,28226.19
2020-01-08,HK.800000,27999.58,28087.92,28198.61,27857.73,0.0,0.0,0,9.655395e+10,-0.826705,28322.06

In [47]:
sdh.get_latest_bars_values('HK.800000', 'close', 10)

time_key
2019-12-23    27906.41
2019-12-24    27864.21
2019-12-27    28225.42
2019-12-30    28319.39
2019-12-31    28189.75
2020-01-02    28543.52
2020-01-03    28451.50
2020-01-06    28226.19
2020-01-07    28322.06
2020-01-08    28087.92
Name: close, dtype: float64

In [5]:
sdh.basicinfo

,lot_size,stock_name,stock_owner,stock_child_type,stock_type,list_time,stock_id,main_contract,last_trade_time,plate_code,plate_name
code,,,,,,,,,,,
HK.00462,4000,天然乳品,None,None,STOCK,2005-06-10,55589761712590,0,,HK.BK1001,乳制品
HK.01117,1000,现代牧业,None,None,STOCK,2010-11-26,64158221468765,0,,HK.BK1001,乳制品
HK.01230,1000,雅士利国际,None,None,STOCK,2010-11-01,64050847286478,0,,HK.BK1001,乳制品
HK.01431,1000,原生态牧业,None,None,STOCK,2013-11-26,68865505625495,0,,HK.BK1001,乳制品
HK.01432,1000,中国圣牧,None,None,STOCK,2014-07-15,69857643070872,0,,HK.BK1001,乳制品
...,...,...,...,...,...,...,...,...,...,...,...
HK.06899,1000,联众,None,None,STOCK,2014-06-30,69793218566899,0,,HK.BK1100,游戏软件
HK.08148,20000,奥柏中国,None,None,STOCK,2004-01-09,53364968660948,0,,HK.BK1100,游戏软件
HK.08267,500,蓝港互动,None,None,STOCK,2014-12-30,70579197583435,0,,HK.BK1100,游戏软件
HK.08282,4000,智傲控股,None,None,STOCK,2016-01-13,8282,0,,HK.BK1100,游戏软件
HK.08345,2000,火岩控股,None,None,STOCK,2016-02-18,8345,0,,HK.BK1100,游戏软件

In [4]:
sdh.hist_kline['HK.800000'].tail(10)

,code,open,close,high,low,pe_ratio,turnover_rate,volume,turnover,change_rate,last_close
time_key,,,,,,,,,,,
2020-05-18,HK.800000,23736.67,23934.77,23952.05,23722.17,0.0,0.0,0,1.094293e+11,0.576952,23797.47
2020-05-19,HK.800000,24489.55,24388.13,24552.55,24314.45,0.0,0.0,0,1.259629e+11,1.894148,23934.77
2020-05-20,HK.800000,24462.90,24399.95,24514.87,24315.75,0.0,0.0,0,1.016919e+11,0.048466,24388.13
2020-05-21,HK.800000,24528.91,24280.03,24528.91,24208.16,0.0,0.0,0,1.242615e+11,-0.491476,24399.95
2020-05-22,HK.800000,23756.91,22930.14,23756.91,22878.26,0.0,0.0,0,1.805460e+11,-5.559672,24280.03
2020-05-25,HK.800000,22725.70,22952.24,22968.65,22519.73,0.0,0.0,0,1.182270e+11,0.096380,22930.14
2020-05-26,HK.800000,23198.34,23384.66,23481.48,23165.49,0.0,0.0,0,1.074647e+11,1.883999,22952.24
2020-05-27,HK.800000,23515.14,23301.36,23515.14,23134.61,0.0,0.0,0,1.108822e+11,NaN,23384.66
2020-05-28,HK.800000,23206.75,23132.76,23451.78,22779.62,0.0,0.0,0,1.326987e+11,NaN,23301.36
2020-05-29,HK.800000,22781.11,22961.47,23089.77,22781.11,0.0,0.0,0,1.789368e+11,NaN,23132.76

In [54]:
ret, plate_list = sdh.quote_ctx.get_plate_list(Market.HK, Plate.INDUSTRY)

In [3]:
sdh.close()

close sqlite ...
close futu ...

2020-05-31 16:40:40,547 [network_manager.py] work:366: Close: conn_id=1